services:
  atheme:
    build:
        context: .
        args:
            BUILD_SERVER_NAME: ${SERVER_NAME}
    image: atheme
    network_mode: "host"
    env_file: "config.env"
    volumes:
        - data:/etc/atheme
        - ./include.conf:/etc/atheme/include.conf:ro
        - ./atheme.conf:/etc/atheme/atheme.conf:ro
        - ssl:/etc/ssl/atheme
        - log:/var/log/atheme
volumes:
    data:
        name: atheme_data
    ssl:
        name: atheme_ssl
    log:
        name: atheme_log
