services:
  atheme:
    build:
        context: .
        args:
            BUILD_SERVER_NAME: ${SERVER_NAME}
    image: atheme
    command: ${DAEMON_FLAGS}
    network_mode: "host"
    env_file: "config.env"
    volumes:
        - ./data:/etc/atheme
        - log:/var/log/atheme
volumes:
    log:
        name: atheme_log
